version: '3'

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
      target: build  # We want maven hot reloading. Do not build all the way for the prod image.
    ports:
      - 8080:8080
    volumes:
      - .:/app
    env_file:
      - .env
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: America/New_York
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgresql/:/docker-entrypoint-initdb.d/

volumes:
  pgdata:
